name: GuardianLink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  http: ^1.1.2
  cloud_firestore: ^4.15.6
  geocoding: ^2.2.0
  image_picker: ^0.8.9
  

  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  permission_handler: ^9.2.0
  webview_flutter: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\assets\logo.png
